### ISSUE TITLE
Can't install extensions

### ISSUE THREAD

**Issue by aphextwins** [UnnoTed/Ungoogled-Chromium-Extension-Installer#1]
![image](https://user-images.githubusercontent.com/37220822/43075509-f6450444-8e35-11e8-84e3-9e14fac23a3c.png)

When i click "Install plugin" in the context menu on a Google Store page, I get the following error.

**Comment by UnnoTed** [comment]
Hi, did you change the flag `chrome://flags/#extension-mime-request-handling` to `Always prompt for install` ?

https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#installing-the-crx-file

**Comment by aphextwins** [comment]
Thanks! works now. i knew there was a flag but i couldnt find it.


![image](https://user-images.githubusercontent.com/37220822/43079467-107fd2ec-8e42-11e8-93fd-094085d9909c.png)

you might wanna add make a quick note of that in the readme.md, cause it makes it read like, "just install it, click the context menu and it works"

**Comment by aphextwins** [comment]
@UnnoTed can it install themes, or do you know how to install themes on ungoogled chromium?

**Comment by aphextwins** [comment]
i keep getting an error:
![image](https://user-images.githubusercontent.com/37220822/43086847-389febf2-8e53-11e8-89c1-6ccde94be07e.png)
even with all my extensions disabled (except this one ofcourse)

**Comment by UnnoTed** [comment]
Re-download and try again, i think it was being caused by query str in the extension's url as if you look at the url from the image there is a `?hl=en` at the extension's id.

**Comment by aphextwins** [comment]
@UnnoTed i uninstalled your extention, restarted chrome, redownloaded the updated version and tried to download a theme again. and got the same error.

However, when i removed `?hl=en` from the URL, it installed the theme!
so i think the new code you added to remove that string from the URL isnt working. atleast not for me.


Windows 10 1803
![image](https://user-images.githubusercontent.com/37220822/43332168-665774b2-917c-11e8-8be0-1e97026578c6.png)
ungoogled chrome compiled by Wyse- (https://github.com/Wyse-/ungoogled-chromium-binaries)
